ruby_on_rails_projects/addressbook/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'contacts#home'
  post '/contacts' => 'contacts#create'
  get '/contacts' => 'contacts#index'
  get '/contacts/new' => 'contacts#new'
  post '/contacts/favourites' => 'contacts#favourites'
  get '/contacts/:id' => 'contacts#show'

  

end

ruby_on_rails_projects/addressbook/app/models/contact.rb
class Contact < ActiveRecord::Base
	validates :name, presence: true, uniqueness: true, length: { minimum: 4 }, format: {with: /\A[A-Za-z0-9]+\z/}
	validates :address, presence: true
	validates :phone_number, length: { maximum: 10}, presence: true
	validates :email, length: {maximum: 20}, uniqueness: true, presence: true
	def self.order_alph
		all.order('name ASC')
	end
end

ruby_on_rails_projects/addressbook/app/controllers/addressbook_controller.rb
class AddressbookController < ApplicationController

end

ruby_on_rails_projects/addressbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby_on_rails_projects/addressbook/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def index
		@contacts = Contact.order_alph
	end
	def show
		id = params[:id]
		@contact = Contact.find(id)
		if @contact.nil?
			render :no_contact_found
		else
			render :show
		end	
	end

	def create 
		@contact = Contact.new(contact_params)
		if @contact.save
			redirect_to "/contacts/#{@contact.id}"
		else
			render :new
		end
	end

	def new
		@contact = Contact.new
		render :new
	end

	def contact_params
		params.require(:contact).permit(:name, :address, :phone_number, :email, :favourites)
	end

	def favourites
		#@contact = Contact.find(favourites)
		@id = params[:parent_id]
		contact = Contact.find(@id)
		contact.update_attribute(:favourites, true)
		render :favourites
	end


end

ruby_on_rails_projects/addressbook/app/helpers/addressbook_helper.rb
module AddressbookHelper
end

ruby_on_rails_projects/addressbook/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_on_rails_projects/addressbook/app/helpers/contacts_helper.rb
module ContactsHelper
end

ruby_on_rails_projects/addressbook/app/views/contacts/favourites.html.erb
<h1> List of your favourites</h1>

<h1><%= @id %></h1>

ruby_on_rails_projects/addressbook/app/views/contacts/index.html.erb
<h1> List of Contacts:</h1>

<ul>
	<% @contacts.each do |contact| %>
		<li>
			<a href="http://localhost:3000/contacts/<%=contact.id%>"><%= contact.name%></a>
		</li>  
		<%= form_for :contact, url: {action: "favourites"} do |f| %>	
			<% if contact.favourites.nil?%>
	 			<%= hidden_field_tag(:parent_id,  contact.id) %>
	 			<%=f.submit "Add to favourites" %>
 			<%end%>
 			<%= contact.favourites %></li> 
		<% end %>
	<%end%>
</ul> 

<%= link_to "Add New Contact", contacts_new_path %>

ruby_on_rails_projects/addressbook/app/views/contacts/new.html.erb
<h1> Create a new Contact</h1>

<% if @contact.errors.messages.present? %>
  <p><%= @contact.errors.messages %></p>
<%end %>

<%= form_for @contact do |f| %>
	<div>
    	<%= f.label :name %>
   	 	<%= f.text_field :name %>
	</div>
	<div>
    	<%= f.label :address %>
  		<%= f.text_area :address %>
  </div>
  <div>
      <%= f.label :phone_number %>
      <%= f.text_area :phone_number %>
  </div>
  <div>
      <%= f.label :email %>
      <%= f.text_area :email %>
  </div>

  <div>
  		<%= f.submit "Create Contact" %>
  	</div>
<% end %>

ruby_on_rails_projects/addressbook/app/views/contacts/show.html.erb
<h1><%= @contact.name %></h1>

<p> Address: <%= @contact.address %></p>
<p> Phone: <%= @contact.phone_number %></p>
<p> Email: <%= @contact.email %></p>
<p> Favourites: <%= @contact.favourites%></p>

ruby_on_rails_projects/addressbook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Addressbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>