ruby_on_rails_projects/ror_timetracking/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sites#home'
  get '/contact'=> 'sites#contact'
  
  resources 'entries', only: [:edit, :update, :destroy]

  resources 'projects' do
    resources 'entries', only: [:create, :new]
  end

end

ruby_on_rails_projects/ror_timetracking/app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :project
	belongs_to :user
end

ruby_on_rails_projects/ror_timetracking/app/models/project.rb
class Project < ActiveRecord::Base
	validates :title, presence: true, uniqueness: true, length: { minimum: 4 }
	
	has_many :entries
	def self.iron_find(num)
		all.where(id: num)
	end

	def self.ordered_alph
		all.limit(5).order("title ASC")
	end

	def self.clean_old
		where("created_at < ?", 2.hours.ago).destroy_all
	end

	def self.last_updated(num)
		all.limit(10).order("updated_at DESC")
	end
end

ruby_on_rails_projects/ror_timetracking/app/models/user.rb
class User < ActiveRecord::Base
	has_many :entry
end

ruby_on_rails_projects/ror_timetracking/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby_on_rails_projects/ror_timetracking/app/controllers/entries_controller.rb
class EntriesController < ApplicationController
	def new
		@project = Project.find(params[:project_id])
		@entry = Entry.new
	end

	def update
		@entry = Entry.find(params[:id])
		project = @entry.project
		if @entry.update(entry_params)
			redirect_to project_path(project)
		else
			render :edit
		end
	end

	def create 
		id = params[:project_id]
		@entry = Entry.new(entry_params)
		@entry.project_id = id

		if @entry.save
			redirect_to project_path(id)
		else
			render :new
		end
	end

	def edit
		@entry = Entry.find(params[:id])
	end

	def destroy
		entry = Entry.find(params[:id])
		entry.destroy
		redirect_to project_path(entry.project)

	end

	private

	def entry_params
		params.require(:entry).permit(:minutes, :hours, :start_date, :comment)
	end
end

ruby_on_rails_projects/ror_timetracking/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.last_updated(10)
	end

	def create 
		@project = Project.new(project_params)
		if @project.save
			flash[:notice] = "Project created succesfully"
			redirect_to project_path(@project)
		else
			render :new
		end
	end

	def update
		@project = Project.find(params[:id])
		if @project.update(project_params)
			flash[:notice] = "Project edited succesfully"
			redirect_to project_path(@project)
		else
			render :edit
		end
	end

	def edit
		@project = Project.find(params[:id])
	end

	def new
		@project = Project.new
		render :new
	end

	def destroy
		project = Project.find(params[:id])
		project.destroy
		redirect_to projects_path
	end

	def show
		id = params[:id]
		@project = Project.find(id)

		if @project.nil?
			render :no_project_found
		else
			@entries = @project.entries
			render :show
		end	
	end
	def project_params
		params.require(:project).permit(:title, :description)
	end
end

ruby_on_rails_projects/ror_timetracking/app/controllers/sites_controller.rb
class SitesController < ApplicationController
	def home
		render :home
	end

	def contact
		render :contact
	end

end

ruby_on_rails_projects/ror_timetracking/app/helpers/application_helper.rb
module ApplicationHelper
	def flash_message
		if flash[:notice]
			content_tag :div, class: 'message alert' do
				content_tag :p do
					flash[:notice]
				end
			end
		
		elsif flash[:alert]
			content_tag :div, class: 'message alert' do
				content_tag :p do
					flash[:alert]
				end
			end
		end
	end
end

ruby_on_rails_projects/ror_timetracking/app/helpers/entries_helper.rb
module EntriesHelper
end

ruby_on_rails_projects/ror_timetracking/app/helpers/projects_helper.rb
module ProjectsHelper
end

ruby_on_rails_projects/ror_timetracking/app/helpers/sites_helper.rb
module SitesHelper
end

ruby_on_rails_projects/ror_timetracking/app/views/entries/edit.html.erb
<h1> Edit Entry </h1>

<%= form_for @entry do |f| %>
	<div>
    	<%= f.label :minutes %>
   	 	<%= f.number_field :minutes %>
	</div>
  	<br>
	<div>
    	<%= f.label :hours %>
  		<%= f.number_field :hours %>
  	</div>
    <br>
    <div>
      <%= f.label :start_date %>
      <%= f.date_field :start_date %>
    </div>
    <br>
    <div>
      <%= f.label :comment %>
      <%= f.text_area :comment %>
    </div>
    <br>
  	<div>
  		<%= f.submit "Update Entry" %>
  	</div>
<% end %>

ruby_on_rails_projects/ror_timetracking/app/views/entries/links.html.erb
<%= link_to "Go To Project List", projects_path %>
<%= link_to "Create Project", new_project_path %>

ruby_on_rails_projects/ror_timetracking/app/views/entries/new.html.erb
<h1> Create a new entry</h1>

<% if @project.errors.messages.present? %>
  <p><%= @project.errors.messages %></p>
<%end %>

<%= form_for [@project, @entry] do |f| %>
	<div>
    	<%= f.label :minutes %>
   	 	<%= f.number_field :minutes %>
	</div>
  <br>
	<div>
    	<%= f.label :hours %>
  		<%= f.number_field :hours %>
  	</div>
    <br>
    <div>
      <%= f.label :start_date %>
      <%= f.date_field :start_date %>
    </div>
    <br>
    <div>
      <%= f.label :comment %>
      <%= f.text_area :comment %>
    </div>
    <br>
  	<div>
  		<%= f.submit "Create Entry" %>
  	</div>
<% end %>

ruby_on_rails_projects/ror_timetracking/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetracking</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ruby_on_rails_projects/ror_timetracking/app/views/projects/_form.html.erb
<% if project.id.nil?%>
  <%button_name = "Create Project" %>
<%else%>
  <%button_name = "Edit Project" %>
<%end%>



<% if project.errors.messages.present? %>
  <p><%= project.errors.messages %></p>
<%end %>

<%= form_for project do |f| %>
	<div>
    	<%= f.label :title %>
   	 	<%= f.text_field :title %>
	</div>
	<div>
    	<%= f.label :description %>
  		<%= f.text_area :description %>
  	</div>
  	<div>
  		<%= f.submit button_name %>
  	</div>
<% end %>

ruby_on_rails_projects/ror_timetracking/app/views/projects/edit.html.erb
<h1> Edit Project </h1>

<% flash_message %>
	

<%= render "form", project: @project %>

ruby_on_rails_projects/ror_timetracking/app/views/projects/index.html.erb
<h1> List of Projects:</h1>

<ul>
	<% @projects.each do |project| %>
	<li> <%= link_to(project.title, project_path(project.id)) %> 
	<!-- <a href="http://localhost:3000/projects/<%=project.id%>"> --> Updated at: <%= project.updated_at.strftime("%H:%M") %>
	<%= link_to "Edit Project", edit_project_path(project) %>
	<%= link_to "Delete Project", project_path(project), method: :delete, data: {confirm: "Are you sure?"} %>
	
</li> 
	<% end %>
</ul>

<!-- <a href = "projects/new"> Add New Project </a> -->
<%= link_to "Create Project", new_project_path %>

ruby_on_rails_projects/ror_timetracking/app/views/projects/new.html.erb
<h1> Create a new project</h1>

<%= render "form" , project: @project %>

ruby_on_rails_projects/ror_timetracking/app/views/projects/show.html.erb
<% flash_message %>

<h1><%= @project.title %></h1>

<%= @project.description %>

<% @entries.each do |entry| %>
	<li><%= "#{entry.project_id}: #{entry.hours} h - #{entry.minutes} m - #{entry.start_date} #{entry.comment}" %>
		<%= link_to("Edit Entry", edit_entry_path(entry))%> 
		<%= link_to "Delete", entry_path(entry), method: "DELETE", data: {confirm: "Are you sure?"} %></li>
<%end%>

<%= link_to "Go To Project List", projects_path %><br>
<%= link_to "Create Entry", new_project_entry_path(@project) %>