ruby_on_rails_projects/auction/auction/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sites#home'
  resources 'products', only: [:destroy, :new, :create, :show]

  resources 'users' do
    resources 'products', only: [:create, :new, :index]
  end

end

ruby_on_rails_projects/auction/auction/app/models/bit.rb
class Bit < ActiveRecord::Base
end

ruby_on_rails_projects/auction/auction/app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :users
	def self.order_alph
		all.order('name ASC')
	end
end

ruby_on_rails_projects/auction/auction/app/models/user.rb
class User < ActiveRecord::Base
	validates :email, presence: true, uniqueness: true
	has_many :products
	def self.order_alph
		all.order('name ASC')
	end
end

ruby_on_rails_projects/auction/auction/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby_on_rails_projects/auction/auction/app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.order_alph
		@user = User.find(params[:user_id])

	end

	def show
		id = params[:id]
		@product = Product.find(id)

		if @product.nil?
			render :no_product_found
		else
			render :show
		end
	end

	def destroy
		product = Product.find(params[:id])
		product.destroy
		redirect_to products_path
	end

	def new
		@user = User.find(params[:user_id])
		@product = Product.new
		
	end

	def create
		id = params[:user_id]
		@product = Product.new(product_params)
		@product.user_id = id
		if @product.save
			flash[:notice] = "Product created succesfully"
			redirect_to user_path(id)
		else
			render :new
		end
	end

	def product_params
		params.require(:product).permit(:name, :description, :deadline)
	end
end

ruby_on_rails_projects/auction/auction/app/controllers/sites_controller.rb
class SitesController < ApplicationController
	def home
		render :home
	end
end

ruby_on_rails_projects/auction/auction/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.order_alph
	end

	def show
		id = params[:id]
		@user = User.find(id)

		if @user.nil?
			render :no_user_found
		else
			render :show
		end
	end

	def destroy
		user = User.find(params[:id])
		user.destroy
		redirect_to users_path
	end

	def new
		@user = User.new
		render :new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "User created succesfully"
			redirect_to user_path(@user)
		else
			render :new
		end
	end

	def user_params
		params.require(:user).permit(:name, :email)
	end
end

ruby_on_rails_projects/auction/auction/app/helpers/application_helper.rb
module ApplicationHelper
	def flash_message
		if flash[:notice]
			content_tag :div, class: 'message alert' do
				content_tag :p do
					flash[:notice]
				end
			end
		
		elsif flash[:alert]
			content_tag :div, class: 'message alert' do
				content_tag :p do
					flash[:alert]
				end
			end
		end
	end
end

ruby_on_rails_projects/auction/auction/app/helpers/products_helper.rb
module ProductsHelper
end

ruby_on_rails_projects/auction/auction/app/helpers/sites_helper.rb
module SitesHelper
end

ruby_on_rails_projects/auction/auction/app/helpers/users_helper.rb
module UsersHelper
end

ruby_on_rails_projects/auction/auction/app/views/products/index.html.erb
<h1> List of Products </h1>
<%= flash_message %>
<ul>
	<% @products.each do |product| %>
		<li>
			Product: <%= link_to(product.name, product_path(product)) %>
			<%= link_to "Delete Product", product_path(product), method: :delete, data: {confirm: "Are you sure?"} %>
		</li>

	<% end %>
</ul>

<%= link_to "Create product", new_user_product_path %>

ruby_on_rails_projects/auction/auction/app/views/products/new.html.erb
<h1> Create a new product</h1>

<% if @user.errors.messages.present? %>
  <p><%= @user.errors.messages %></p>
<%end %>

<%= form_for [@user, @product] do |f| %>
	<div>
    	<%= f.label :name %>
   	 	<%= f.text_field :name %>
	</div>
  <br>
	<div>
    	<%= f.label :description %>
  		<%= f.text_area :description %>
  	</div>
    <br>
    <div>
      <%= f.label :deadline %>
      <%= f.date_field :deadline %>
    </div>
    <br>

  	<div>
  		<%= f.submit "Create Product" %>
  	</div>
<% end %>

ruby_on_rails_projects/auction/auction/app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<%= flash_message %>
<p> Description: <%= @product.description %></p>
<p> Deadline: <%= @product.deadline %></p>

<%= link_to "Go To User List", users_path %><br>

ruby_on_rails_projects/auction/auction/app/views/users/_form.html.erb
<% if user.new_record?%>
  <%button_name = "Create User" %>
<%else%>
  <%button_name = "Edit User" %>
<%end%>

<% if user.errors.messages.present? %>
  <p><%= user.errors.messages %></p>
<%end %>

<%= form_for user do |f| %>
	<div>
    	<%= f.label :name %>
   	 	<%= f.text_field :name %>
	</div>
	<div>
    	<%= f.label :email %>
  		<%= f.text_field :email %>
  	</div>
  	<div>
  		<%= f.submit button_name %>
  	</div>
<% end %>

ruby_on_rails_projects/auction/auction/app/views/users/index.html.erb
<h1> List of Users </h1>
<%= flash_message %>
<ul>
	<% @users.each do |user| %>
		<li>
			Username: <%= link_to(user.name, user_path(user)) %>
			<%= link_to "Delete User", user_path(user), method: :delete, data: {confirm: "Are you sure?"} %>
		</li>

	<% end %>
</ul>

<%= link_to "Create User", new_user_path %>

ruby_on_rails_projects/auction/auction/app/views/users/new.html.erb
<h1> Create a New User</h1>

<%= render "form" , user: @user %>

ruby_on_rails_projects/auction/auction/app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= flash_message %>
<p> Email: <%= @user.email %></p>

<%= link_to "Go To User List", users_path %><br>
<%= link_to "Go To User Products List", user_products_path(@user) %>