ruby_on_rails_projects/music_concerts/concerts/config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root to: "concerts#home"
  resources 'concerts'

end

ruby_on_rails_projects/music_concerts/concerts/app/models/concert.rb
class Concert < ActiveRecord::Base
	validates :band, presence: true, uniqueness: true
	validates :venue, presence: true, uniqueness: true
	validates :city, presence: true, uniqueness: true
	validates :datetime, presence: true
	validates :price, presence: true, uniqueness: true
	validates :description, presence: true, uniqueness: true
	def self.order_alph
		all.order('band ASC')
	end
end

ruby_on_rails_projects/music_concerts/concerts/app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	attr_accessible :username, :email, :password, :password_confirmation
	
  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true #password_confirmation attr
  validates_length_of :password, :in => 6..20, :on => :create

before_save :encrypt_password
after_save :clear_password
def encrypt_password
  if password.present?
    self.salt = BCrypt::Engine.generate_salt
    self.encrypted_password= BCrypt::Engine.hash_secret(password, salt)
  end
end
def clear_password
  self.password = nil
end
end

ruby_on_rails_projects/music_concerts/concerts/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby_on_rails_projects/music_concerts/concerts/app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
	def home
		@concerts = Concert.limit(6).order("created_at DESC")
		@concerts_month = Concert.limit(14).order("created_at ASC")

	end

	def index
		@concerts = Concert.order_alph

	end

	def show
		id = params[:id]
		@concert = Concert.find(id)

		if @concert.nil?
			render :no_concert_found
		else
			render :show
		end
	end

	def new
		@concert = Concert.new
		render :new
	end

	def create
		@concert = Concert.new(concert_params)
		if @concert.save
			flash[:notice] = "Concert created succesfully"
			redirect_to concert_path(@concert)
		else
			render :new
		end
	end

	def concert_params
		params.require(:concert).permit(:band, :venue, :city, :datetime, :price, :description)
	end
end

ruby_on_rails_projects/music_concerts/concerts/app/controllers/users_controller.rb
class UsersController < ApplicationController
   def new
    @user = User.new 
  end
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "You signed up successfully"
      flash[:color]= "valid"
    else
      flash[:notice] = "Form is invalid"
      flash[:color]= "invalid"
    end
    render "new"
  end

end

ruby_on_rails_projects/music_concerts/concerts/app/helpers/application_helper.rb
module ApplicationHelper
	def flash_message
		if flash[:notice]
			content_tag :div, class: 'message alert' do
				content_tag :p do
					flash[:notice]
				end
			end
		
		elsif flash[:alert]
			content_tag :div, class: 'message alert' do
				content_tag :p do
					flash[:alert]
				end
			end
		end
	end
end

ruby_on_rails_projects/music_concerts/concerts/app/helpers/concerts_helper.rb
module ConcertsHelper
end

ruby_on_rails_projects/music_concerts/concerts/app/helpers/users_helper.rb
module UsersHelper
end

ruby_on_rails_projects/music_concerts/concerts/app/views/layouts/_footerbar.html.erb
<footer>
<nav class="navbar navbar-default navbar-fixed-bottom">

        <p class="bootom"> IRONHACK © 2015</p>
  
</nav>
</footer>

ruby_on_rails_projects/music_concerts/concerts/app/views/layouts/_navbar.html.erb
<header>

<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href ="/">Music Concert Network</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Concerts List", concerts_path %><span class="sr-only">(current)</span></a></li>
        <li><a href="concerts/new">Add a new Concert</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

ruby_on_rails_projects/music_concerts/concerts/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Concerts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<%= render "/layouts/navbar" %>
	

<%= yield %>


<%= render "/layouts/footerbar" %>

</body>
</html>

ruby_on_rails_projects/music_concerts/concerts/app/views/users/new.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    <p> Username:</br> <%= f.text_field :username%> </p>
    <p> Email:</br> <%= f.text_field :email%> </p>
    <p> Password:</br> <%= f.password_field :password%></p>
    <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p>
    <%= f.submit :Signup %>
  <% end %>
  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li>* <%= message_error %></li>
    <% end %>
    </ul>
  <% end %>
</div>